### PR TITLE
Added some new messages for Lolo as per discussion

### PR DESCRIPTION
**Pull request by nilsbore**
@NiklasRolleberg Please have a look and say if this makes sense. In particular, I'm wondering if the scalar types of `ThrusterRPM` and `ThrusterFeedback` could be ints instead of floats if that is what they actually are (particularly RPM)?

### CODE REVIEW

**Comment by NiklasRolleberg** [comment]
I think it makes sense. There is no need for the rpm to be a float, int works just as well, but for torque and current it's probably best to stick with floats.

**Comment by nilsbore** [comment]
@NiklasRolleberg ok, changed rpm to `int32`.

**Comment by nilsbore** [comment]
@Jollerprutt I added `DualThrusterRPM` and `DualThrusterFeedback` here also. Was I supposed to add any other messages?

**Comment by nilsbore** [comment]
@NiklasRolleberg @Jollerprutt merged!

**Pull request merged**
