### PR TITLE
Proposal for a common SMARC AUV ROS interface

### PR DESCRIPTION
**Pull request by nilsbore**
Please leave a comment if you have any thoughts. This PR contains the [proposal document](https://github.com/smarc-project/smarc_msgs/blob/interface/README.rst) as well as the new message, service and action types that define the interface.

### CODE REVIEW

**Comment by nilsbore** [comment]
TF services added in https://github.com/smarc-project/smarc_navigation/pull/48

**Comment by NiklasRolleberg** [comment]
I have a few questions.

If the vehicle has controllers that are not a part if the ROS system, should they still be a part of the /vehicle/ctrl/ group and listen to the commands sent on those topics? On lolo for example you can send a heading setpoint directly to the vehicle without having a controller running in ROS, but you can also have a controller running in ROS and send rudder angles to the vehicle in order to control the heading.

What units should the controllers expect? degrees, radians, meters etc

**Comment by nilsbore** [comment]
@NiklasRolleberg Good points! I expanded the [Controllers section](https://github.com/smarc-project/smarc_msgs/blob/interface/README.rst#controller-interfaces) and added a new [Units section](https://github.com/smarc-project/smarc_msgs/blob/interface/README.rst#units).

**Comment by NiklasRolleberg** [comment]
I think it would be a good idea to have a few topics that describe the attitude in pitch, roll and yaw to make it easier to implement simple controllers and to make it easier to debug without having to read quaternions or use tf.

**Comment by nilsbore** [comment]
@NiklasRolleberg That's a good point and something I would like to have, but I think it can be implemented on top of this interface. One can use TF or the odometry topic to get this information.

**Pull request merged**
